import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./ui/Header";
import Footer from "./ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rick and Morty's characters book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    { name: "Japa", href: "/" },
    { name: "Capa", href: "/characters" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page-wrapper px-5">
          <Header />
          <main className="mx-auto w-full lg:w-1/2">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
